# Create a sample stream directory
mkdir -p backend/data/streams/sample-stream

# Create sample HLS segments (these would normally be generated by a video encoder)
echo "Sample TS segment data" > backend/data/streams/sample-stream/segment000.ts
echo "Sample TS segment data" > backend/data/streams/sample-stream/segment001.ts
echo "Sample TS segment data" > backend/data/streams/sample-stream/segment002.ts